create database college;
use college;
create table students(sno int,name varchar(20),cource varchar(20),eno int,fname varchar(20),mname varchar(20),city varchar(20),blood varchar(20),shift int,phone VARCHAR(12));
SELECT * FROM students;
INSERT INTO students VALUES(1,'kamar','BCA',12020,'N.H khan','Tahira','Delhi','B+',1,7557662302);
INSERT INTO students VALUES(1,'Shruti','BCA',22020,'Sunil verma','neelam','Delhi','O-',1,7557222302);
INSERT INTO students VALUES(1,'Muskan','BCA',32020,'ashok','nandita','Delhi','B+',1,9567223026);
INSERT INTO students VALUES(1,'Isha','BCA',42020,'ashish','mrs.verma','Delhi','o+',1,9567223026);
INSERT INTO students VALUES(1,'mahiva','BCA',52020,'MR.Bansal','mrs.Bansal','Delhi','A+',1,8568242026);
INSERT INTO students VALUES(1,'vasnhu','BCA',62020,'MR.Negi','mrs.Negi','Delhi','B+',1,7591242026);
INSERT INTO students VALUES(1,'Vedant','BCA',72020,'MR.Kumar','mrs.Kumar','Delhi','B+',1,8591242026);
SELECT * from students where eno BETWEEN 10000 AND 30000;
INSERT INTO students VALUES(7,'Vedant','BCA',72020,'MR.Kumar','mrs.Kumar','Old Delhi','B+',1,8591242026);
SELECT * from students where city in ('delhi');
SELECT * from students where eno not BETWEEN 10000 AND 30000;
SELECT * from students where city not in ('delhi');
UPDATE  students set sno=2 where name="shruti";
-- UPDATE  students set eno=220 where name="shruti";
DELETE from students where name="vasnhu";
DELETE from students where name="mahiva";
UPDATE  students set sno=3 where name="isha";
SELECT * from  students WHERE eno BETWEEN 30000 and 40000 AND not sno IN(2,3,4);
UPDATE  students set sno=4 where name="muskan";
UPDATE  students set sno=4 where name="isha";
UPDATE  students set sno=5 where name="mahiva";
UPDATE  students set sno=6 where name="vanshu";
UPDATE  students set sno=8 where city="old Delhi";
UPDATE  students set sno=7 where city="Delhi";
UPDATE  students set sno=2 where name="shruti";
UPDATE  students set sno=4 where name="isha";
UPDATE  students set sno=3 where name="muskan";
UPDATE  students set sno=5 where name="mahiva";
UPDATE  students set sno=6 where name="vasnhu";
UPDATE  students set sno=8 where city="old Delhi";
UPDATE  students set sno=8 where name="vedant";
UPDATE  students set sno=7 where name="vedant";
UPDATE  students set sno=1 where name="kamar";
UPDATE students set sno=8 WHERE city="old Delhi";
UPDATE students set eno=82020 WHERE city="old Delhi";
alter table students ADD PRIMARY KEY (eno);